import { SkinTreatmentCatalogueItem } from '../models/SkinTreatment';

export const SKIN_TREATMENTS: SkinTreatmentCatalogueItem[] = [
  {
    "id": 1,
    "sku": "GLW-001",
    "name": "HydraFacial Signature + LED",
    "displayName": "HydraGlow Facial",
    "category": "Skin Glow Therapy",
    "subCategory": "Glow Facials",
    "procedureType": "Non-invasive Vortex-Fusion Facial",
    "tier": "Entry",
    "price": 4999,
    "description": "Full face standard. No area variation. Includes LED boost as default for premium positioning."
  },
  {
    "id": 2,
    "sku": "GLW-002",
    "name": "HydraFacial Deluxe + Boosters + Lymphatic Drainage",
    "displayName": "HydraGlow Luxe",
    "category": "Skin Glow Therapy",
    "subCategory": "Glow Facials",
    "procedureType": "Advanced Multi-Step Resurfacing Facial",
    "tier": "Core",
    "price": 8999,
    "description": "Full face + neck zone. Includes premium boosters (brightening/anti-aging). LED + lymphatic massage bundled."
  },
  {
    "id": 3,
    "sku": "GLW-003",
    "name": "Pressurized Oxygen Infusion Facial",
    "displayName": "Oxygen Radiance Facial",
    "category": "Skin Glow Therapy",
    "subCategory": "Glow Facials",
    "procedureType": "Oxygen Infusion Therapy",
    "tier": "Entry",
    "price": 3999,
    "description": "Full face only. No area variants. Quick 30-min protocol ideal for first-time clients."
  },
  {
    "id": 4,
    "sku": "GLW-004",
    "name": "Q-Switch Nd:YAG Carbon Laser Facial",
    "displayName": "Carbon Laser Peel (Hollywood Glow)",
    "category": "Skin Glow Therapy",
    "subCategory": "Laser Glow",
    "procedureType": "Non-Ablative Laser Facial",
    "tier": "Core",
    "price": 6999,
    "description": "Full face standard. Carbon lotion + Q-switch laser. Premium variant of facials using laser technology."
  },
  {
    "id": 5,
    "sku": "GLW-005",
    "name": "PRP + Microneedling Facial Rejuvenation",
    "displayName": "Vampire Glow Facial",
    "category": "Skin Glow Therapy",
    "subCategory": "Bio Glow",
    "procedureType": "Autologous PRP Microneedling",
    "tier": "Premium",
    "price": 14999,
    "description": "Full face. PRP extraction + centrifuge + microneedling delivery. Internal cost: ₹3-4K consumables, rest is margin."
  },
  {
    "id": 6,
    "sku": "GLW-006",
    "name": "IPL (Intense Pulsed Light) Skin Rejuvenation",
    "displayName": "Photo Radiance Therapy",
    "category": "Skin Glow Therapy",
    "subCategory": "Light Therapy",
    "procedureType": "Broad-Spectrum Pulsed Light",
    "tier": "Core",
    "price": 5999,
    "description": "Full face weighted avg. Small areas (cheeks only) would be ₹3K internal, full face ₹6K. Pricing at full face default."
  },
  {
    "id": 7,
    "sku": "GLW-007",
    "name": "Clinical-Grade Medi Facial with Active Serums",
    "displayName": "MediFacial Pro",
    "category": "Skin Glow Therapy",
    "subCategory": "Clinical Facials",
    "procedureType": "Dermatologist-Supervised Medical Facial",
    "tier": "Entry",
    "price": 3499,
    "description": "Full face. Uses clinical-grade products. Dermatologist supervision is the differentiator from salon facials."
  },
  {
    "id": 8,
    "sku": "ACN-001",
    "name": "Superficial Chemical Peel (Salicylic/Glycolic)",
    "displayName": "Acne Control Peel",
    "category": "Acne Control Therapy",
    "subCategory": "Acne Peels",
    "procedureType": "Superficial Chemoexfoliation",
    "tier": "Entry",
    "price": 2999,
    "description": "Full face standard. Peel concentration customized by dermatologist. No area split — acne is usually multi-zone."
  },
  {
    "id": 9,
    "sku": "ACN-002",
    "name": "Medium-Depth TCA Chemical Peel",
    "displayName": "Deep Acne Purge Peel",
    "category": "Acne Control Therapy",
    "subCategory": "Acne Peels",
    "procedureType": "Medium-Depth Chemoexfoliation",
    "tier": "Core",
    "price": 5999,
    "description": "Full face. TCA peels require MD supervision. Includes post-peel care kit value (₹500 internal cost added)."
  },
  {
    "id": 10,
    "sku": "ACN-003",
    "name": "Intralesional Corticosteroid Injection",
    "displayName": "Cystic Acne Injection Therapy",
    "category": "Acne Control Therapy",
    "subCategory": "Acne Injections",
    "procedureType": "Intralesional Steroid Administration",
    "tier": "Entry",
    "price": 2999,
    "description": "Per-session (covers multiple lesions). Internal: ₹1K cost per session. No area split — session covers all active cysts."
  },
  {
    "id": 11,
    "sku": "ACN-004",
    "name": "Professional Comedone Extraction + Peel",
    "displayName": "Comedone Detox Session",
    "category": "Acne Control Therapy",
    "subCategory": "Acne Detox",
    "procedureType": "Manual Sterile Comedone Extraction",
    "tier": "Entry",
    "price": 2499,
    "description": "Full face. Extraction + light peel combo. Bundled to avoid \"₹500 extraction\" perception from local clinics."
  },
  {
    "id": 12,
    "sku": "ACN-005",
    "name": "Non-Ablative Laser for Active Acne + Inflammation",
    "displayName": "Acne Laser Clear",
    "category": "Acne Control Therapy",
    "subCategory": "Acne Laser",
    "procedureType": "Non-Ablative Laser Acne Therapy",
    "tier": "Core",
    "price": 7999,
    "description": "Full face. Laser = premium positioning within acne category. Internal cost higher due to equipment time allocation."
  },
  {
    "id": 13,
    "sku": "PIG-001",
    "name": "Q-Switch Nd:YAG Laser Toning",
    "displayName": "Q-Switch Laser Brightening",
    "category": "Pigmentation Correction",
    "subCategory": "Laser Brightening",
    "procedureType": "Non-Ablative Q-Switched Laser",
    "tier": "Core",
    "price": 7999,
    "description": "Weighted avg: small area ₹4K, full face ₹8K, neck add-on ₹3K. Default = full face. 6-8 sessions recommended."
  },
  {
    "id": 14,
    "sku": "PIG-002",
    "name": "Cosmelan/Dermamelan Professional Depigmentation",
    "displayName": "Cosmelan Depigmentation Program",
    "category": "Pigmentation Correction",
    "subCategory": "Depigmentation",
    "procedureType": "Professional Depigmentation Mask System",
    "tier": "Premium",
    "price": 29999,
    "description": "One in-clinic session + home care kit (kit value ₹8-10K). No area split — full face standard. Single treatment model."
  },
  {
    "id": 15,
    "sku": "PIG-003",
    "name": "Medium-Depth Depigmentation Chemical Peel",
    "displayName": "Brightening Peel Therapy",
    "category": "Pigmentation Correction",
    "subCategory": "Brightening Peels",
    "procedureType": "Targeted Chemoexfoliation for Melanin",
    "tier": "Core",
    "price": 5499,
    "description": "Full face standard. Specialized peels (Jessner/modified) for pigmentation. Different from acne peels in formulation."
  },
  {
    "id": 16,
    "sku": "PIG-004",
    "name": "IV Glutathione Infusion Therapy",
    "displayName": "Glutathione Glow Drip",
    "category": "Pigmentation Correction",
    "subCategory": "IV Brightening",
    "procedureType": "Intravenous Antioxidant Infusion",
    "tier": "Core",
    "price": 7999,
    "description": "N/A — IV drip is systemic. No area logic. Session = 30-60 min drip. 8-12 sessions for visible results."
  },
  {
    "id": 17,
    "sku": "PIG-005",
    "name": "High-Dose Vitamin C IV Infusion",
    "displayName": "Vitamin C Radiance Drip",
    "category": "Pigmentation Correction",
    "subCategory": "IV Brightening",
    "procedureType": "Intravenous Ascorbic Acid Therapy",
    "tier": "Core",
    "price": 5999,
    "description": "N/A — systemic IV. No area logic. Often combined with glutathione. Positioned slightly below glutathione for bundling."
  },
  {
    "id": 18,
    "sku": "PIG-006",
    "name": "Multi-Vitamin + Biotin + Glutathione IV Cocktail",
    "displayName": "Beauty Wellness Drip",
    "category": "Pigmentation Correction",
    "subCategory": "IV Brightening",
    "procedureType": "Multi-Nutrient IV Infusion",
    "tier": "Core",
    "price": 8999,
    "description": "N/A — systemic IV. Premium cocktail combining multiple actives. Positioned as the \"all-in-one\" IV option."
  },
  {
    "id": 19,
    "sku": "AGE-001",
    "name": "Botulinum Toxin Type A (Allergan/Botox)",
    "displayName": "Botox Precision (Allergan)",
    "category": "Anti-Aging Therapy",
    "subCategory": "Neuromodulators",
    "procedureType": "Botulinum Toxin Injection",
    "tier": "Premium",
    "price": 24999,
    "description": "Weighted: single area ₹12K, full face (3 areas) ₹30K. ₹24,999 = aspirational mid-point. Per-area upsell possible internally."
  },
  {
    "id": 20,
    "sku": "AGE-002",
    "name": "Botulinum Toxin Type A (Non-Allergan: Innotox/Stunnox)",
    "displayName": "Botox Essentials",
    "category": "Anti-Aging Therapy",
    "subCategory": "Neuromodulators",
    "procedureType": "Botulinum Toxin Injection (Alternative)",
    "tier": "Core",
    "price": 14999,
    "description": "Same area logic as Allergan but lower-cost brand. Weighted average across typical 2-area treatment."
  },
  {
    "id": 21,
    "sku": "AGE-003",
    "name": "Hyaluronic Acid Dermal Filler (Allergan/Juvederm)",
    "displayName": "Dermal Sculpt (Premium Fillers)",
    "category": "Anti-Aging Therapy",
    "subCategory": "Dermal Fillers",
    "procedureType": "HA Filler Injection",
    "tier": "Premium",
    "price": 34999,
    "description": "Per 1ml syringe pricing. Lips ₹25K, cheeks ₹35K, jawline ₹40K → ₹34,999 = weighted mid-premium point."
  },
  {
    "id": 22,
    "sku": "AGE-004",
    "name": "Hyaluronic Acid Dermal Filler (Galderma/EPTQ)",
    "displayName": "Dermal Refresh (Standard Fillers)",
    "category": "Anti-Aging Therapy",
    "subCategory": "Dermal Fillers",
    "procedureType": "HA Filler Injection (Standard)",
    "tier": "Premium",
    "price": 24999,
    "description": "Per 1ml syringe. Standard HA filler brands. Same area logic but positioned below premium fillers."
  },
  {
    "id": 23,
    "sku": "AGE-005",
    "name": "High-Intensity Focused Ultrasound Skin Tightening",
    "displayName": "HIFU Face Lift",
    "category": "Anti-Aging Therapy",
    "subCategory": "Non-Surgical Lift",
    "procedureType": "Focused Ultrasound Tissue Remodeling",
    "tier": "Premium",
    "price": 34999,
    "description": "Weighted: lower face ₹25K, full face ₹45K, face+neck ₹60K. ₹34,999 = full face default. Upsell neck internally."
  },
  {
    "id": 24,
    "sku": "AGE-006",
    "name": "PDO/PLA Thread Lift Procedure",
    "displayName": "Thread Lift Contour",
    "category": "Anti-Aging Therapy",
    "subCategory": "Non-Surgical Lift",
    "procedureType": "Absorbable Thread Suspension",
    "tier": "Premium",
    "price": 49999,
    "description": "Mid-face average. Brow ₹25K, mid-face ₹50K, full face+neck ₹120K. ₹49,999 = standard mid-face anchor."
  },
  {
    "id": 25,
    "sku": "AGE-007",
    "name": "Thermage FLX Monopolar RF Skin Tightening",
    "displayName": "Thermage Skin Renewal",
    "category": "Anti-Aging Therapy",
    "subCategory": "Non-Surgical Lift",
    "procedureType": "Monopolar Radiofrequency Remodeling",
    "tier": "Premium",
    "price": 89999,
    "description": "Full face standard. Single-session treatment. Highest-cost device on platform. Thermage tips = ₹30-40K internal cost."
  },
  {
    "id": 26,
    "sku": "AGE-008",
    "name": "Micro-Focused Ultrasound with Visualization (MFU-V)",
    "displayName": "Ultherapy Precision Lift",
    "category": "Anti-Aging Therapy",
    "subCategory": "Non-Surgical Lift",
    "procedureType": "MFU-V Collagen Neogenesis",
    "tier": "Premium",
    "price": 69999,
    "description": "Full face weighted. Brow ₹30K, face ₹70K, face+neck ₹100K. ₹69,999 = full face standard."
  },
  {
    "id": 27,
    "sku": "DSR-001",
    "name": "Fractional CO2 Laser Skin Resurfacing",
    "displayName": "CO2 Laser Resurfacing (Deep Skin Repair)",
    "category": "Deep Skin Repair",
    "subCategory": "Laser Resurfacing",
    "procedureType": "Ablative Fractional Laser Resurfacing",
    "tier": "Premium",
    "price": 29999,
    "description": "Full face standard. Small area (cheeks) ₹15K, full face ₹30K. ₹29,999 = full face default. Most intensive laser."
  },
  {
    "id": 28,
    "sku": "DSR-002",
    "name": "Erbium:YAG Fractional Laser Resurfacing",
    "displayName": "Erbium Laser Refinement",
    "category": "Deep Skin Repair",
    "subCategory": "Laser Resurfacing",
    "procedureType": "Non-Ablative Fractional Laser",
    "tier": "Premium",
    "price": 18999,
    "description": "Full face standard. Less intensive than CO2. Weighted avg from small area ₹8K, full face ₹15K with premium margin."
  },
  {
    "id": 29,
    "sku": "DSR-003",
    "name": "Subcision + TCA CROSS + Filler for Acne Scars",
    "displayName": "Scar Revision Therapy",
    "category": "Deep Skin Repair",
    "subCategory": "Scar Treatment",
    "procedureType": "Multi-Modal Scar Revision",
    "tier": "Premium",
    "price": 18999,
    "description": "Full face/affected zones. Combines subcision + cross + micro-filler. Bundled as single \"therapy\" vs itemized."
  },
  {
    "id": 30,
    "sku": "DSR-004",
    "name": "Dermatologist-Led Microneedling (Dermapen)",
    "displayName": "Microneedling Pro",
    "category": "Deep Skin Repair",
    "subCategory": "Collagen Induction",
    "procedureType": "Percutaneous Collagen Induction Therapy",
    "tier": "Core",
    "price": 6999,
    "description": "Full face standard. Small area ₹3K, full face ₹7K, with PRP add-on ₹12K. Base pricing at full face without PRP."
  },
  {
    "id": 31,
    "sku": "DSR-005",
    "name": "Platelet-Rich Plasma Facial Rejuvenation + Microneedling",
    "displayName": "PRP Skin Regeneration",
    "category": "Deep Skin Repair",
    "subCategory": "Regenerative",
    "procedureType": "Autologous PRP Intradermal Therapy",
    "tier": "Core",
    "price": 12999,
    "description": "Full face. PRP extraction + centrifuge + microneedling delivery. Internal cost ₹3-4K. Premium on \"own blood\" narrative."
  },
  {
    "id": 32,
    "sku": "DSR-006",
    "name": "Profhilo/Skin Booster HA Bio-Remodeling",
    "displayName": "Skin Booster Hydra-Infusion",
    "category": "Deep Skin Repair",
    "subCategory": "Bio-Remodeling",
    "procedureType": "Injectable HA Bio-Remodeling",
    "tier": "Premium",
    "price": 24999,
    "description": "Full face standard (5 injection points per side). No small-area variant — technique requires full distribution."
  },
  {
    "id": 33,
    "sku": "TGT-001",
    "name": "Radiofrequency Skin Tightening (Bipolar/Tripolar)",
    "displayName": "RF Skin Tightening",
    "category": "Skin Tightening Therapy",
    "subCategory": "RF Treatments",
    "procedureType": "Radiofrequency Collagen Stimulation",
    "tier": "Core",
    "price": 9999,
    "description": "Weighted: jawline ₹6K, full face ₹10K, face+neck ₹15K. ₹9,999 = full face default position."
  },
  {
    "id": 34,
    "sku": "TGT-002",
    "name": "Microneedling Radiofrequency (Morpheus8/MNRF)",
    "displayName": "MNRF Micro-Sculpt",
    "category": "Skin Tightening Therapy",
    "subCategory": "Advanced RF",
    "procedureType": "Microneedling with Bipolar RF Energy",
    "tier": "Premium",
    "price": 18999,
    "description": "Full face standard. Combines microneedling + RF. Small area ₹10K, full face ₹18K, body ₹25K. Priced at face."
  },
  {
    "id": 35,
    "sku": "TGT-003",
    "name": "Mesotherapy (Vitamin/HA/Antioxidant Micro-Injection)",
    "displayName": "Mesotherapy Rejuvenation",
    "category": "Skin Tightening Therapy",
    "subCategory": "Micro-Injection",
    "procedureType": "Intradermal Meso-Cocktail Injection",
    "tier": "Core",
    "price": 7999,
    "description": "Full face standard. Customizable cocktails. No area split — face is default. Neck add-on billed as separate session."
  },
  {
    "id": 36,
    "sku": "LHR-001",
    "name": "Diode/Nd:YAG Laser Hair Removal (Small Area)",
    "displayName": "Laser Hair Reduction — Starter",
    "category": "Laser Hair Reduction",
    "subCategory": "Hair Laser",
    "procedureType": "Selective Photothermolysis (Small Zone)",
    "tier": "Entry",
    "price": 3999,
    "description": "Small areas: upper lip, chin, underarms, sideburns. Internal range ₹1.5-5K. ₹3,999 = weighted premium average for small zone."
  },
  {
    "id": 37,
    "sku": "LHR-002",
    "name": "Soprano ICE/Titanium Laser Hair Removal (Medium Area)",
    "displayName": "Laser Hair Reduction — Essential",
    "category": "Laser Hair Reduction",
    "subCategory": "Hair Laser",
    "procedureType": "Selective Photothermolysis (Medium Zone)",
    "tier": "Core",
    "price": 8999,
    "description": "Medium areas: full arms, half legs, bikini line. Internal range ₹5-15K. ₹8,999 = weighted premium mid-point."
  },
  {
    "id": 38,
    "sku": "LHR-003",
    "name": "Soprano Titanium Full Body Laser Hair Removal",
    "displayName": "Laser Hair Reduction — Complete",
    "category": "Laser Hair Reduction",
    "subCategory": "Hair Laser",
    "procedureType": "Selective Photothermolysis (Full Body)",
    "tier": "Premium",
    "price": 24999,
    "description": "Full body single session. Internal range ₹18-36K. ₹24,999 = premium positioning with ₹25K just-below anchor."
  },
  {
    "id": 39,
    "sku": "LHR-004",
    "name": "Soprano/Diode Laser Full Face Hair Removal",
    "displayName": "Laser Hair Reduction — Face",
    "category": "Laser Hair Reduction",
    "subCategory": "Hair Laser",
    "procedureType": "Selective Photothermolysis (Facial Zone)",
    "tier": "Core",
    "price": 5999,
    "description": "Full face: upper lip + chin + cheeks + sideburns + jawline. Internal range ₹3-7.5K. ₹5,999 = full face premium."
  },
  {
    "id": 40,
    "sku": "ADV-001",
    "name": "Growth Factor Concentrate (GFC) Facial Therapy",
    "displayName": "GFC Skin Regeneration",
    "category": "Advanced Skin Therapies",
    "subCategory": "Regenerative",
    "procedureType": "Autologous Growth Factor Therapy",
    "tier": "Premium",
    "price": 18999,
    "description": "Full face. GFC extraction + activation + injection. Internal cost ₹5-7K per session. High-margin procedure."
  },
  {
    "id": 41,
    "sku": "ADV-002",
    "name": "Exosome-Based Skin Rejuvenation Therapy",
    "displayName": "Exosome Skin Revival",
    "category": "Advanced Skin Therapies",
    "subCategory": "Next-Gen",
    "procedureType": "Exosome Cell Signaling Therapy",
    "tier": "Premium",
    "price": 34999,
    "description": "Full face. Cutting-edge treatment. Limited availability = exclusivity. Internal cost ₹12-15K per session."
  },
  {
    "id": 42,
    "sku": "ADV-003",
    "name": "Electrocautery/RF Ablation of Benign Skin Growths",
    "displayName": "Wart & Mole Precision Removal",
    "category": "Advanced Skin Therapies",
    "subCategory": "Minor Procedures",
    "procedureType": "Electrosurgical Ablation",
    "tier": "Entry",
    "price": 2999,
    "description": "Per session (covers multiple lesions). Internal ₹500-2K. Flat session fee avoids per-lesion complexity on frontend."
  },
  {
    "id": 43,
    "sku": "ADV-004",
    "name": "Q-Switch Nd:YAG Laser Tattoo Removal",
    "displayName": "Laser Tattoo Erasure",
    "category": "Advanced Skin Therapies",
    "subCategory": "Laser Removal",
    "procedureType": "Q-Switched Laser Tattoo Fragmentation",
    "tier": "Core",
    "price": 6999,
    "description": "Per session. Small tattoo ₹3K, medium ₹5K, large ₹10K. ₹6,999 = medium tattoo weighted default."
  },
  {
    "id": 44,
    "sku": "ADV-005",
    "name": "Diamond-Tip Microdermabrasion",
    "displayName": "Microdermabrasion Refresh",
    "category": "Advanced Skin Therapies",
    "subCategory": "Surface Treatment",
    "procedureType": "Mechanical Epidermal Resurfacing",
    "tier": "Entry",
    "price": 2999,
    "description": "Full face. No area variation. Quick 20-min procedure. Low consumable cost = high margin at any price."
  },
  {
    "id": 45,
    "sku": "HAIR-001",
    "name": "Platelet-Rich Plasma Scalp Injection for Hair Regrowth",
    "displayName": "PRP Scalp Therapy",
    "category": "Hair Restoration",
    "subCategory": "Hair PRP",
    "procedureType": "Autologous PRP Intradermal Scalp Therapy",
    "tier": "Core",
    "price": 9999,
    "description": "Scalp-wide injection. No area split — full scalp is default. 4-6 sessions standard protocol."
  },
  {
    "id": 46,
    "sku": "HAIR-002",
    "name": "Growth Factor Concentrate Scalp Therapy",
    "displayName": "GFC Hair Regrowth",
    "category": "Hair Restoration",
    "subCategory": "Hair GFC",
    "procedureType": "Autologous GFC Scalp Injection",
    "tier": "Premium",
    "price": 18999,
    "description": "Full scalp. GFC positioned as \"next-gen PRP\" internally. Higher growth factor concentration = premium justified."
  },
  {
    "id": 47,
    "sku": "HAIR-003",
    "name": "QR678 Neo Growth Factor Scalp Injection",
    "displayName": "QR678 Hair Revival",
    "category": "Hair Restoration",
    "subCategory": "Hair Growth Factor",
    "procedureType": "Proprietary Growth Factor Injection",
    "tier": "Core",
    "price": 12999,
    "description": "Full scalp. Indian-developed proprietary therapy. 6-8 sessions standard."
  },
  {
    "id": 48,
    "sku": "HAIR-004",
    "name": "Follicular Unit Extraction Hair Transplant",
    "displayName": "Hair Transplant (FUE)",
    "category": "Hair Restoration",
    "subCategory": "Surgical",
    "procedureType": "FUE Hair Transplant Surgery",
    "tier": "Premium",
    "price": 89999,
    "description": "Starting price. Per graft: ₹50-100. Average 2000 grafts = ₹1-2L. ₹89,999 = starting anchor for consultation conversion."
  }
];
