import { TreatmentCatalogueItem } from '../../models/Treatment';

export const FACIAL_TREATMENTS: TreatmentCatalogueItem[] = [
  {
    "id": 1,
    "name": "Lip Hydration Filler",
    "displayName": "Lip Hydra Glow",
    "category": "Lip Enhancement",
    "tier": "Entry",
    "price": 14999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Low-viscosity HA filler for deep lip moisture and subtle plump"
  },
  {
    "id": 2,
    "name": "Lip Volume Enhancement",
    "displayName": "Lip Volume Boost",
    "category": "Lip Enhancement",
    "tier": "Core",
    "price": 24999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "HA filler to add volume, fullness, and shape definition to thin lips"
  },
  {
    "id": 3,
    "name": "Lip Reshaping / Contouring",
    "displayName": "Lip Contour & Define",
    "category": "Lip Enhancement",
    "tier": "Core",
    "price": 29999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Precise filler placement to define cupid's bow, vermilion border, and lip contours"
  },
  {
    "id": 4,
    "name": "Lip Symmetry Correction",
    "displayName": "Lip Symmetry Restore",
    "category": "Lip Enhancement",
    "tier": "Core",
    "price": 34999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Targeted filler to balance asymmetric upper and lower lips"
  },
  {
    "id": 5,
    "name": "Lip Flip (Botox)",
    "displayName": "Lip Flip",
    "category": "Lip Enhancement",
    "tier": "Entry",
    "price": 8999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Botox injected into orbicularis oris to subtly flip upper lip outward"
  },
  {
    "id": 6,
    "name": "Surgical Lip Lift (Bullhorn)",
    "displayName": "Surgical Lip Lift",
    "category": "Lip Enhancement",
    "tier": "Surgical",
    "price": 74999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Excision of skin below nose to shorten philtrum and show more upper lip vermilion"
  },
  {
    "id": 7,
    "name": "Lip Reduction Surgery",
    "displayName": "Lip Reduction Surgery",
    "category": "Lip Enhancement",
    "tier": "Surgical",
    "price": 64999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Surgical reduction of excessively large lips for proportional size"
  },
  {
    "id": 8,
    "name": "Lip Augmentation (Fat Transfer)",
    "displayName": "Lip Augmentation (Fat Graft)",
    "category": "Lip Enhancement",
    "tier": "Surgical",
    "price": 84999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Autologous fat harvested and injected into lips for permanent volume"
  },
  {
    "id": 9,
    "name": "Lip Commissure Lift",
    "displayName": "Lip Corner Lift",
    "category": "Lip Enhancement",
    "tier": "Surgical",
    "price": 64999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Surgical lifting of downturned mouth corners for pleasant resting expression"
  },
  {
    "id": 10,
    "name": "Jawline Definition Filler",
    "displayName": "Jawline Define",
    "category": "Jawline & Chin Sculpting",
    "tier": "Premium",
    "price": 54999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Volumizing filler along mandible to create sharper jawline contour"
  },
  {
    "id": 11,
    "name": "Chin Projection Filler",
    "displayName": "Chin Projection",
    "category": "Jawline & Chin Sculpting",
    "tier": "Core",
    "price": 38999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Filler placed at chin to add forward projection and facial balance"
  },
  {
    "id": 12,
    "name": "Chin Dimple Smoothing (Botox)",
    "displayName": "Chin Smooth",
    "category": "Jawline & Chin Sculpting",
    "tier": "Entry",
    "price": 9999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Botox into mentalis muscle to reduce orange peel chin dimpling"
  },
  {
    "id": 13,
    "name": "Lower Face Contouring Package",
    "displayName": "Lower Face Sculpt",
    "category": "Jawline & Chin Sculpting",
    "tier": "Premium",
    "price": 89999,
    "procedureType": "non-surgical",
    "sessions": "1-2",
    "description": "Combined jawline + chin + jowl correction for complete lower face sculpting"
  },
  {
    "id": 14,
    "name": "Masseter Slimming (Botox)",
    "displayName": "V-Shape Slim",
    "category": "Jawline & Chin Sculpting",
    "tier": "Core",
    "price": 28999,
    "procedureType": "non-surgical",
    "sessions": "2-3",
    "description": "Botox into masseter muscles to slim wide/square jawline for V-shape face"
  },
  {
    "id": 15,
    "name": "Chin Projection Filler (Mild Retrognathia)",
    "displayName": "Chin Correct (Class II)",
    "category": "Jawline & Chin Sculpting",
    "tier": "Core",
    "price": 39999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Filler-based chin projection for mild Class II retrognathia"
  },
  {
    "id": 16,
    "name": "Jawline + Chin Combo Correction",
    "displayName": "Jawline + Chin Combo",
    "category": "Jawline & Chin Sculpting",
    "tier": "Premium",
    "price": 79999,
    "procedureType": "non-surgical",
    "sessions": "1-2",
    "description": "Combined jawline and chin filler correction for comprehensive lower face harmony"
  },
  {
    "id": 17,
    "name": "Filler + Botox Lower Face Rebalance",
    "displayName": "Lower Face Rebalance",
    "category": "Jawline & Chin Sculpting",
    "tier": "Premium",
    "price": 59999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Strategic combo of fillers for structure + Botox for muscle refinement in lower face"
  },
  {
    "id": 18,
    "name": "Masseter + Jaw Angle Slimming (Botox)",
    "displayName": "Jaw Angle Slim (Advanced)",
    "category": "Jawline & Chin Sculpting",
    "tier": "Premium",
    "price": 44999,
    "procedureType": "non-surgical",
    "sessions": "2-3",
    "description": "Advanced Botox slimming targeting both masseter and jaw angle for maximum V-shape"
  },
  {
    "id": 19,
    "name": "Buccal Fat Removal",
    "displayName": "Buccal Fat Removal",
    "category": "Jawline & Chin Sculpting",
    "tier": "Surgical",
    "price": 49999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Excision of buccal fat pads via intraoral incision for cheek slimming"
  },
  {
    "id": 20,
    "name": "Chin Implant (Augmentation)",
    "displayName": "Chin Implant",
    "category": "Jawline & Chin Sculpting",
    "tier": "Surgical",
    "price": 169999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Silicone/Medpor implant for permanent chin projection and facial balance"
  },
  {
    "id": 21,
    "name": "Genioplasty (Surgical Chin Advancement)",
    "displayName": "Class II \u2014 Genioplasty (Chin Advancement)",
    "category": "Jawline & Chin Sculpting",
    "tier": "Surgical",
    "price": 199999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Chin bone cut and advanced forward for moderate Class II overbite correction"
  },
  {
    "id": 22,
    "name": "Chin Implant (Alloplastic Genioplasty)",
    "displayName": "Class II \u2014 Chin Implant (Alloplastic)",
    "category": "Jawline & Chin Sculpting",
    "tier": "Surgical",
    "price": 179999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Alloplastic implant for Class II chin projection; cosmetic correction"
  },
  {
    "id": 23,
    "name": "Class II Orthognathic Surgery (Mandibular Advancement)",
    "displayName": "Class II \u2014 Jaw Advancement Surgery (BSSO)",
    "category": "Jawline & Chin Sculpting",
    "tier": "Surgical",
    "price": 249999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "BSSO to advance entire lower jaw forward; corrects severe Class II overbite; improves chewing, speech, facial profile"
  },
  {
    "id": 24,
    "name": "Sliding Genioplasty",
    "displayName": "Sliding Genioplasty",
    "category": "Jawline & Chin Sculpting",
    "tier": "Surgical",
    "price": 219999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Chin bone repositioned via sliding osteotomy for precise projection/setback"
  },
  {
    "id": 25,
    "name": "Jaw Reduction Surgery (V-Line)",
    "displayName": "V-Line Jaw Surgery",
    "category": "Jawline & Chin Sculpting",
    "tier": "Surgical",
    "price": 229999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Surgical shaving/contouring of mandibular angle for V-shape jawline"
  },
  {
    "id": 26,
    "name": "Jaw Implant (Mandibular Angle)",
    "displayName": "Jaw Angle Implant",
    "category": "Jawline & Chin Sculpting",
    "tier": "Surgical",
    "price": 249999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Custom or stock implants along mandibular angle for jawline definition"
  },
  {
    "id": 27,
    "name": "Facial Liposuction (Submental/Jowl)",
    "displayName": "Face Lipo (Chin & Jowl)",
    "category": "Jawline & Chin Sculpting",
    "tier": "Surgical",
    "price": 69999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Targeted liposuction of double chin and jowl fat for facial slimming"
  },
  {
    "id": 28,
    "name": "Bichectomy + Jawline Lipo Combo",
    "displayName": "Bichectomy + Lipo Combo",
    "category": "Jawline & Chin Sculpting",
    "tier": "Surgical",
    "price": 89999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Combined buccal fat removal + submental liposuction for comprehensive face slimming"
  },
  {
    "id": 29,
    "name": "Nose Bridge Enhancement",
    "displayName": "Nose Bridge Enhance",
    "category": "Nose Correction",
    "tier": "Premium",
    "price": 34999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "HA filler along nasal dorsum to raise flat bridge and improve profile"
  },
  {
    "id": 30,
    "name": "Nose Tip Refinement",
    "displayName": "Nose Tip Refine",
    "category": "Nose Correction",
    "tier": "Core",
    "price": 32999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Precise filler at nasal tip for lifting, defining, or de-rounding bulbous tip"
  },
  {
    "id": 31,
    "name": "Nose Symmetry Correction",
    "displayName": "Nose Symmetry Correct",
    "category": "Nose Correction",
    "tier": "Premium",
    "price": 36999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Targeted filler to camouflage deviated or asymmetric nose without surgery"
  },
  {
    "id": 32,
    "name": "Complete Non-Surgical Nose Job",
    "displayName": "Complete Nose Reshape",
    "category": "Nose Correction",
    "tier": "Premium",
    "price": 49999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Comprehensive non-surgical reshaping: bridge lift + tip refinement + symmetry"
  },
  {
    "id": 33,
    "name": "Nose Thread Lift",
    "displayName": "Nose Thread Lift",
    "category": "Nose Correction",
    "tier": "Premium",
    "price": 34999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "PDO threads in nose for structural lift of bridge and tip without filler"
  },
  {
    "id": 34,
    "name": "Primary Cosmetic Rhinoplasty (Open)",
    "displayName": "Rhinoplasty (Open)",
    "category": "Nose Correction",
    "tier": "Surgical",
    "price": 149999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Open rhinoplasty to reshape nose structure: hump removal, tip refinement, width reduction"
  },
  {
    "id": 35,
    "name": "Closed Rhinoplasty",
    "displayName": "Rhinoplasty (Closed)",
    "category": "Nose Correction",
    "tier": "Surgical",
    "price": 129999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Endonasal approach with no external incision for minor structural corrections"
  },
  {
    "id": 36,
    "name": "Tip Rhinoplasty (Tipplasty)",
    "displayName": "Tip Rhinoplasty",
    "category": "Nose Correction",
    "tier": "Surgical",
    "price": 89999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Surgical refinement of only the nasal tip without altering bridge or bone"
  },
  {
    "id": 37,
    "name": "Septorhinoplasty (Functional + Cosmetic)",
    "displayName": "Septorhinoplasty",
    "category": "Nose Correction",
    "tier": "Surgical",
    "price": 179999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Combined septum correction for breathing + cosmetic reshaping of nose"
  },
  {
    "id": 38,
    "name": "Revision Rhinoplasty",
    "displayName": "Revision Rhinoplasty",
    "category": "Nose Correction",
    "tier": "Surgical",
    "price": 249999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Secondary corrective surgery to fix issues from prior rhinoplasty"
  },
  {
    "id": 39,
    "name": "Tear Trough Filler (Under Eye)",
    "displayName": "Tear Trough Revive",
    "category": "Under Eye & Midface",
    "tier": "Core",
    "price": 34999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Light HA filler under eyes to correct hollows, dark circles, and tired look"
  },
  {
    "id": 40,
    "name": "Cheek Volume Filler",
    "displayName": "Cheek Volume Sculpt",
    "category": "Under Eye & Midface",
    "tier": "Core",
    "price": 38999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "HA filler to restore cheek volume, create cheekbone definition, and lift midface"
  },
  {
    "id": 41,
    "name": "Non-Surgical Midface Lift",
    "displayName": "Non-Surgical Midface Lift",
    "category": "Under Eye & Midface",
    "tier": "Premium",
    "price": 59999,
    "procedureType": "non-surgical",
    "sessions": "1-2",
    "description": "Strategic filler placement in midface to lift sagging cheeks and reduce nasolabial folds"
  },
  {
    "id": 42,
    "name": "Under Eye PRP/GFC",
    "displayName": "Under Eye Rejuvenation",
    "category": "Under Eye & Midface",
    "tier": "Entry",
    "price": 11999,
    "procedureType": "non-surgical",
    "sessions": "3-4",
    "description": "PRP or GFC injected under eyes to improve skin quality and reduce dark circles"
  },
  {
    "id": 43,
    "name": "Under Eye Skin Booster",
    "displayName": "Under Eye Hydra Boost",
    "category": "Under Eye & Midface",
    "tier": "Core",
    "price": 21999,
    "procedureType": "non-surgical",
    "sessions": "2-3",
    "description": "Micro-injections of HA skin booster for under-eye hydration and texture"
  },
  {
    "id": 44,
    "name": "Midface Filler Augmentation (Camouflage)",
    "displayName": "Midface Volume Restore",
    "category": "Under Eye & Midface",
    "tier": "Premium",
    "price": 54999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Midface filler augmentation to camouflage Class III jaw appearance"
  },
  {
    "id": 45,
    "name": "Cheek Implant (Malar Augmentation)",
    "displayName": "Cheek Implant",
    "category": "Under Eye & Midface",
    "tier": "Surgical",
    "price": 149999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Silicone/Medpor implants placed over cheekbone for permanent cheek enhancement"
  },
  {
    "id": 46,
    "name": "Upper Blepharoplasty",
    "displayName": "Upper Eyelid Lift",
    "category": "Under Eye & Midface",
    "tier": "Surgical",
    "price": 59999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Removal of excess upper eyelid skin and fat to eliminate drooping/hooding"
  },
  {
    "id": 47,
    "name": "Lower Blepharoplasty",
    "displayName": "Lower Eyelid Lift",
    "category": "Under Eye & Midface",
    "tier": "Surgical",
    "price": 84999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Removal or repositioning of under-eye fat bags; skin tightening below eyes"
  },
  {
    "id": 48,
    "name": "Quad Blepharoplasty (Upper + Lower)",
    "displayName": "Complete Eyelid Rejuvenation",
    "category": "Under Eye & Midface",
    "tier": "Surgical",
    "price": 139999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Combined upper and lower eyelid surgery for comprehensive eye rejuvenation"
  },
  {
    "id": 49,
    "name": "Asian Double Eyelid Surgery",
    "displayName": "Double Eyelid Surgery",
    "category": "Under Eye & Midface",
    "tier": "Surgical",
    "price": 89999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Creation of upper eyelid crease in monolid patients for double eyelid appearance"
  },
  {
    "id": 50,
    "name": "Ptosis Correction (Droopy Eyelid)",
    "displayName": "Ptosis Correction",
    "category": "Under Eye & Midface",
    "tier": "Surgical",
    "price": 84999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Surgical correction of drooping upper eyelid by tightening levator muscle"
  },
  {
    "id": 51,
    "name": "Forehead Lines Botox",
    "displayName": "Forehead Smooth",
    "category": "Botox-Based Treatments",
    "tier": "Entry",
    "price": 9999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Botox to frontalis muscle to smooth horizontal forehead wrinkles"
  },
  {
    "id": 52,
    "name": "Frown Lines (Glabellar) Botox",
    "displayName": "Frown Line Erase",
    "category": "Botox-Based Treatments",
    "tier": "Entry",
    "price": 8999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Botox between eyebrows to relax glabellar muscles causing 11 lines"
  },
  {
    "id": 53,
    "name": "Crow's Feet Botox",
    "displayName": "Crow's Feet Refresh",
    "category": "Botox-Based Treatments",
    "tier": "Entry",
    "price": 11999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Botox around outer eye corners to reduce fan-shaped smile lines"
  },
  {
    "id": 54,
    "name": "Upper Face Botox Package",
    "displayName": "Upper Face Refresh Package",
    "category": "Botox-Based Treatments",
    "tier": "Core",
    "price": 24999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Combined forehead + glabella + crow's feet Botox in one session"
  },
  {
    "id": 55,
    "name": "Masseter Botox (Jaw Slimming)",
    "displayName": "Jaw Slim (Masseter)",
    "category": "Botox-Based Treatments",
    "tier": "Core",
    "price": 28999,
    "procedureType": "non-surgical",
    "sessions": "2-3",
    "description": "Botox into masseter muscles bilaterally for V-shape face slimming"
  },
  {
    "id": 56,
    "name": "Gummy Smile Correction (Botox)",
    "displayName": "Gummy Smile Fix",
    "category": "Botox-Based Treatments",
    "tier": "Entry",
    "price": 8999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Botox into LLSAN muscle to reduce excessive gum show when smiling"
  },
  {
    "id": 57,
    "name": "Botox Eyebrow Lift",
    "displayName": "Brow Lift (Botox)",
    "category": "Botox-Based Treatments",
    "tier": "Entry",
    "price": 9999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Strategic Botox to elevate brow position and open eye area"
  },
  {
    "id": 58,
    "name": "Nefertiti Lift (Neck Botox)",
    "displayName": "Nefertiti Neck Define",
    "category": "Botox-Based Treatments",
    "tier": "Core",
    "price": 21999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Botox along platysmal bands for sharper jawline and reduced neck bands"
  },
  {
    "id": 59,
    "name": "Bunny Lines Botox",
    "displayName": "Bunny Lines Smooth",
    "category": "Botox-Based Treatments",
    "tier": "Entry",
    "price": 5999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Botox on nose to reduce wrinkles appearing on nose bridge when smiling"
  },
  {
    "id": 60,
    "name": "Lip Lines Botox (Smoker Lines)",
    "displayName": "Lip Lines Smooth",
    "category": "Botox-Based Treatments",
    "tier": "Entry",
    "price": 8999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Micro-Botox around lips to soften vertical perioral lines"
  },
  {
    "id": 61,
    "name": "Hyperhidrosis Botox (Facial)",
    "displayName": "Facial Sweat Control",
    "category": "Botox-Based Treatments",
    "tier": "Core",
    "price": 34999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Botox for excessive facial sweating"
  },
  {
    "id": 62,
    "name": "MesoBotox (Baby Botox / Skin Botox)",
    "displayName": "Glass Skin Botox",
    "category": "Botox-Based Treatments",
    "tier": "Core",
    "price": 18999,
    "procedureType": "non-surgical",
    "sessions": "2-3",
    "description": "Micro-doses of Botox injected superficially for pore reduction and glass skin glow"
  },
  {
    "id": 63,
    "name": "Facial Asymmetry \u2014 Botox for Muscle Imbalance",
    "displayName": "Asymmetry Correct (Botox)",
    "category": "Botox-Based Treatments",
    "tier": "Core",
    "price": 18999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Botox to correct facial muscle imbalance causing visible asymmetry"
  },
  {
    "id": 64,
    "name": "Alarplasty (Nostril Reduction)",
    "displayName": "Alarplasty (Nostril Refine)",
    "category": "Botox-Based Treatments",
    "tier": "Surgical",
    "price": 64999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Surgical narrowing of wide nostrils by removing wedge of alar skin"
  },
  {
    "id": 65,
    "name": "PRP Facial (Vampire Facial)",
    "displayName": "Vampire Glow Facial",
    "category": "Skin Boosters / Rejuvenation",
    "tier": "Entry",
    "price": 11999,
    "procedureType": "non-surgical",
    "sessions": "3-4",
    "description": "PRP derived from patient blood micro-needled or injected for skin rejuvenation"
  },
  {
    "id": 66,
    "name": "GFC Facial (Growth Factor Concentrate)",
    "displayName": "GFC Radiance Facial",
    "category": "Skin Boosters / Rejuvenation",
    "tier": "Entry",
    "price": 14999,
    "procedureType": "non-surgical",
    "sessions": "3-4",
    "description": "Concentrated growth factors from blood for advanced collagen stimulation"
  },
  {
    "id": 67,
    "name": "Microneedling + PRP Combo",
    "displayName": "Micro-Glow Therapy",
    "category": "Skin Boosters / Rejuvenation",
    "tier": "Entry",
    "price": 14999,
    "procedureType": "non-surgical",
    "sessions": "3-4",
    "description": "Dermapen microneedling combined with PRP for enhanced collagen induction"
  },
  {
    "id": 68,
    "name": "Skin Boosters (Profhilo)",
    "displayName": "Profhilo Bio-Remodel",
    "category": "Skin Boosters / Rejuvenation",
    "tier": "Core",
    "price": 34999,
    "procedureType": "non-surgical",
    "sessions": 2,
    "description": "Bio-remodeling HA treatment that hydrates skin and stimulates collagen/elastin"
  },
  {
    "id": 69,
    "name": "Skin Boosters (Restylane/NCTF)",
    "displayName": "Skin Hydra Boost (Restylane)",
    "category": "Skin Boosters / Rejuvenation",
    "tier": "Core",
    "price": 24999,
    "procedureType": "non-surgical",
    "sessions": "2-3",
    "description": "Micro-injection of HA skin boosters for deep hydration and glow"
  },
  {
    "id": 70,
    "name": "PDRN Skin Booster (Salmon DNA)",
    "displayName": "Salmon DNA Rejuvenation",
    "category": "Skin Boosters / Rejuvenation",
    "tier": "Core",
    "price": 24999,
    "procedureType": "non-surgical",
    "sessions": "3-4",
    "description": "Polynucleotide injection derived from salmon DNA for skin repair and regeneration"
  },
  {
    "id": 71,
    "name": "Exosome Therapy (Face)",
    "displayName": "Exosome Regeneration",
    "category": "Skin Boosters / Rejuvenation",
    "tier": "Premium",
    "price": 44999,
    "procedureType": "non-surgical",
    "sessions": "2-3",
    "description": "Stem cell-derived exosome injections for advanced skin regeneration"
  },
  {
    "id": 72,
    "name": "Sculptra (Collagen Biostimulator)",
    "displayName": "Sculptra Collagen Program",
    "category": "Skin Boosters / Rejuvenation",
    "tier": "Premium",
    "price": 54999,
    "procedureType": "non-surgical",
    "sessions": "2-3",
    "description": "Poly-L-lactic acid injections to stimulate gradual collagen production over months"
  },
  {
    "id": 73,
    "name": "PDO Thread Lift (Face)",
    "displayName": "Thread Lift \u2014 Face",
    "category": "Thread Lift / Tightening",
    "tier": "Premium",
    "price": 69999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Absorbable PDO threads inserted to mechanically lift sagging facial tissues"
  },
  {
    "id": 74,
    "name": "PDO Thread Lift (Neck)",
    "displayName": "Thread Lift \u2014 Neck",
    "category": "Thread Lift / Tightening",
    "tier": "Premium",
    "price": 54999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "PDO threads for neck band reduction and neck skin tightening"
  },
  {
    "id": 75,
    "name": "Thread Lift (Eyebrow)",
    "displayName": "Thread Lift \u2014 Brow",
    "category": "Thread Lift / Tightening",
    "tier": "Premium",
    "price": 34999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "PDO threads to lift drooping eyebrows and reduce hooding"
  },
  {
    "id": 76,
    "name": "HIFU Facial Contouring (Full Face)",
    "displayName": "HIFU Lift \u2014 Full Face",
    "category": "HIFU / Non-Surgical Lift",
    "tier": "Premium",
    "price": 44999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "High-intensity focused ultrasound for non-surgical face lift and skin tightening"
  },
  {
    "id": 77,
    "name": "HIFU Jawline Contouring",
    "displayName": "HIFU Jawline Contour",
    "category": "HIFU / Non-Surgical Lift",
    "tier": "Core",
    "price": 29999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "HIFU specifically targeted at jawline for definition and jowl reduction"
  },
  {
    "id": 78,
    "name": "Radiesse (CaHA Filler)",
    "displayName": "Radiesse Structural Filler",
    "category": "HIFU / Non-Surgical Lift",
    "tier": "Core",
    "price": 42999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Calcium hydroxylapatite filler for deep structural support and collagen stimulation"
  },
  {
    "id": 79,
    "name": "Full Face Filler Plan (3-Zone)",
    "displayName": "Face Harmony \u2014 3 Zone",
    "category": "Full Face Harmony",
    "tier": "Signature",
    "price": 109999,
    "procedureType": "non-surgical",
    "sessions": "1-2",
    "description": "Strategic filler in cheeks + jawline + chin for overall facial balance"
  },
  {
    "id": 80,
    "name": "Full Face Filler Plan (5-Zone)",
    "displayName": "Face Harmony \u2014 5 Zone",
    "category": "Full Face Harmony",
    "tier": "Signature",
    "price": 179999,
    "procedureType": "non-surgical",
    "sessions": "2-3",
    "description": "Comprehensive filler: temples + cheeks + nasolabial + jawline + chin"
  },
  {
    "id": 81,
    "name": "Facial Balancing (Proportional Correction)",
    "displayName": "Golden Ratio Balancing",
    "category": "Full Face Harmony",
    "tier": "Signature",
    "price": 89999,
    "procedureType": "non-surgical",
    "sessions": "2-3",
    "description": "Assessment-based filler placement focusing on golden ratio facial proportions"
  },
  {
    "id": 82,
    "name": "Combination Contouring (Filler + Botox)",
    "displayName": "Contour + Relax Combo",
    "category": "Full Face Harmony",
    "tier": "Premium",
    "price": 64999,
    "procedureType": "non-surgical",
    "sessions": "1-2",
    "description": "Strategic combo of fillers for structure + Botox for muscle refinement"
  },
  {
    "id": 83,
    "name": "Nasolabial Fold Correction",
    "displayName": "Smile Line Soften",
    "category": "Full Face Harmony",
    "tier": "Core",
    "price": 31999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Filler injected to soften deep smile lines from nose to mouth corners"
  },
  {
    "id": 84,
    "name": "Marionette Line Correction",
    "displayName": "Marionette Line Lift",
    "category": "Full Face Harmony",
    "tier": "Core",
    "price": 31999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Filler at mouth corners to reduce sad/angry resting expression"
  },
  {
    "id": 85,
    "name": "Temple Volume Restoration",
    "displayName": "Temple Restore",
    "category": "Full Face Harmony",
    "tier": "Core",
    "price": 31999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Filler at temples to restore lost volume and reduce hollow/gaunt appearance"
  },
  {
    "id": 86,
    "name": "Liquid Facelift (Comprehensive)",
    "displayName": "The Liquid Facelift",
    "category": "Full Face Harmony",
    "tier": "Signature",
    "price": 179999,
    "procedureType": "non-surgical",
    "sessions": "2-3",
    "description": "Full non-surgical facelift using fillers + Botox + threads in one master plan"
  },
  {
    "id": 87,
    "name": "Facial Asymmetry \u2014 Unilateral Filler Correction",
    "displayName": "Asymmetry Correct (Filler)",
    "category": "Full Face Harmony",
    "tier": "Core",
    "price": 39999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Unilateral filler correction for visible facial asymmetry"
  },
  {
    "id": 88,
    "name": "Facial Asymmetry \u2014 Comprehensive Rebalancing Package",
    "displayName": "Asymmetry Rebalancing Package",
    "category": "Full Face Harmony",
    "tier": "Signature",
    "price": 94999,
    "procedureType": "non-surgical",
    "sessions": "2-3",
    "description": "Comprehensive multi-area correction for significant facial asymmetry"
  },
  {
    "id": 89,
    "name": "Full Profile Camouflage Package",
    "displayName": "Profile Camouflage Package",
    "category": "Full Face Harmony",
    "tier": "Signature",
    "price": 99999,
    "procedureType": "non-surgical",
    "sessions": "1-2",
    "description": "Full profile non-surgical camouflage for jaw class defects"
  },
  {
    "id": 90,
    "name": "Chin + Nose Profile Balancing",
    "displayName": "Chin + Nose Profile Balance",
    "category": "Full Face Harmony",
    "tier": "Premium",
    "price": 69999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Combined chin and nose filler for overall side-profile harmony"
  },
  {
    "id": 91,
    "name": "PRP + Dermal Filler Combo",
    "displayName": "Glow + Volume Restore",
    "category": "Combination Treatments",
    "tier": "Premium",
    "price": 44999,
    "procedureType": "non-surgical",
    "sessions": "2-3",
    "description": "PRP for skin quality + filler for volume restoration in same session"
  },
  {
    "id": 92,
    "name": "Laser + Filler Contouring Combo",
    "displayName": "Laser Sculpt + Contour",
    "category": "Combination Treatments",
    "tier": "Premium",
    "price": 64999,
    "procedureType": "non-surgical",
    "sessions": "3-5",
    "description": "Laser resurfacing for skin + fillers for structural enhancement"
  },
  {
    "id": 93,
    "name": "Glow + Sculpting Package",
    "displayName": "Glow & Sculpt Package",
    "category": "Combination Treatments",
    "tier": "Core",
    "price": 38999,
    "procedureType": "non-surgical",
    "sessions": "2-3",
    "description": "Chemical peel/medi-facial + strategic filler for glow and contour"
  },
  {
    "id": 94,
    "name": "MNRF + Filler Combo",
    "displayName": "MNRF + Volume Combo",
    "category": "Combination Treatments",
    "tier": "Premium",
    "price": 54999,
    "procedureType": "non-surgical",
    "sessions": "3-4",
    "description": "Microneedling RF for skin tightening + fillers for volume replacement"
  },
  {
    "id": 95,
    "name": "Clear Aligner + Chin Filler Combo",
    "displayName": "Aligner + Chin Harmony",
    "category": "Combination Treatments",
    "tier": "Signature",
    "price": 169999,
    "procedureType": "non-surgical",
    "sessions": "multi",
    "description": "Clear aligner orthodontics combined with chin filler for comprehensive profile correction"
  },
  {
    "id": 96,
    "name": "Post-Orthognathic Aesthetic Refinement Package",
    "displayName": "Post-Surgery Refinement",
    "category": "Combination Treatments",
    "tier": "Premium",
    "price": 79999,
    "procedureType": "non-surgical",
    "sessions": "2-3",
    "description": "Post-jaw-surgery aesthetic refinement with fillers and Botox"
  },
  {
    "id": 97,
    "name": "Pre-Surgery Profile Simulation (Filler Trial)",
    "displayName": "Profile Simulation (Filler)",
    "category": "Combination Treatments",
    "tier": "Core",
    "price": 34999,
    "procedureType": "non-surgical",
    "sessions": 1,
    "description": "Temporary filler placement to simulate surgical outcome before committing to surgery"
  },
  {
    "id": 98,
    "name": "Mandibular Setback Surgery (Orthognathic)",
    "displayName": "Class III \u2014 Mandibular Setback Surgery",
    "category": "Combination Treatments",
    "tier": "Surgical",
    "price": 299999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Overdeveloped lower jaw surgically pushed back to correct severe Class III underbite; improves chewing, speech, and facial aesthetics"
  },
  {
    "id": 99,
    "name": "Class III Maxillary Advancement Surgery (Le Fort I)",
    "displayName": "Class III \u2014 Maxillary Advancement (Le Fort I)",
    "category": "Combination Treatments",
    "tier": "Surgical",
    "price": 249999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Underdeveloped upper jaw moved forward via Le Fort I osteotomy; corrects Class III underbite caused by maxillary deficiency"
  },
  {
    "id": 100,
    "name": "Double Jaw Surgery (Bimaxillary)",
    "displayName": "Class III \u2014 Double Jaw Surgery (Bimaxillary)",
    "category": "Combination Treatments",
    "tier": "Surgical",
    "price": 499999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Both jaws surgically repositioned simultaneously; corrects severe skeletal Class III underbite; most complex facial surgery"
  },
  {
    "id": 101,
    "name": "Mini Facelift (MACS Lift)",
    "displayName": "Mini Facelift",
    "category": "Combination Treatments",
    "tier": "Surgical",
    "price": 199999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Limited incision facelift targeting jowls and lower face with shorter recovery"
  },
  {
    "id": 102,
    "name": "Full Facelift (SMAS / Deep Plane)",
    "displayName": "Full Facelift (Deep Plane)",
    "category": "Combination Treatments",
    "tier": "Surgical",
    "price": 399999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Comprehensive surgical lift of midface, jowls, and neck via deep plane technique"
  },
  {
    "id": 103,
    "name": "Neck Lift (Platysmaplasty)",
    "displayName": "Neck Lift",
    "category": "Combination Treatments",
    "tier": "Surgical",
    "price": 199999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Surgical tightening of platysma muscles and removal of excess neck skin"
  },
  {
    "id": 104,
    "name": "Brow Lift (Endoscopic)",
    "displayName": "Brow Lift (Surgical)",
    "category": "Combination Treatments",
    "tier": "Surgical",
    "price": 169999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Minimally invasive endoscopic lifting of drooped eyebrows and forehead"
  },
  {
    "id": 105,
    "name": "Midface Lift (Surgical)",
    "displayName": "Midface Lift (Surgical)",
    "category": "Combination Treatments",
    "tier": "Surgical",
    "price": 229999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Surgical elevation of cheek fat pad and malar tissues for midface rejuvenation"
  },
  {
    "id": 106,
    "name": "Dimpleplasty (Dimple Creation)",
    "displayName": "Dimpleplasty",
    "category": "Combination Treatments",
    "tier": "Surgical",
    "price": 34999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Surgical creation of permanent dimples on cheeks via intraoral technique"
  },
  {
    "id": 107,
    "name": "Otoplasty (Ear Correction)",
    "displayName": "Otoplasty (Ear Reshape)",
    "category": "Combination Treatments",
    "tier": "Surgical",
    "price": 89999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Surgical pinning back of protruding ears or reshaping of ear cartilage"
  },
  {
    "id": 108,
    "name": "Facial Fat Grafting (Full Face)",
    "displayName": "Facial Fat Grafting",
    "category": "Combination Treatments",
    "tier": "Surgical",
    "price": 119999,
    "procedureType": "surgical",
    "sessions": 1,
    "description": "Autologous fat harvested and strategically injected into multiple face zones"
  },
  {
    "id": 109,
    "name": "Scar Revision Surgery (Facial)",
    "displayName": "Facial Scar Revision",
    "category": "Combination Treatments",
    "tier": "Surgical",
    "price": 49999,
    "procedureType": "surgical",
    "sessions": "1-3",
    "description": "Surgical improvement of facial scars from acne, injury, or prior surgery"
  },
  {
    "id": 110,
    "name": "Facial Feminization Surgery (FFS)",
    "displayName": "Facial Feminization (FFS)",
    "category": "Combination Treatments",
    "tier": "Surgical",
    "price": 549999,
    "procedureType": "surgical",
    "sessions": "2-4",
    "description": "Combination of forehead contouring, rhinoplasty, jaw reduction for feminine facial features"
  }
];
